### ISSUE TITLE
Wrapping of functions with optional arguments does not work as expected

### ISSUE THREAD

**Issue by gawhelan** [gawhelan/midwrap#1]
Functions that accept optional arguments don't behave as expected when wrapped. If they are invoked with one or more optional arguments omitted then errors get thrown in the middleware functions.

Example:
```js
// Function to concatenate multiple strings
const join = midwrap((parts, separator) => parts.join(separator || ' ');

// Add middleware to use double separators
join.use((parts, separator, next) => {
  const sep = separator || ' ';
  return next(parts, sep + sep));
});

join(['Jane', 'Bloggs'], '.'); // => 'Jane..Bloggs';
join(['Jane', 'Bloggs']); // => TypeError 'next is not a function'
```

See this commit for a failing test demonstrating the issue: 977e1403

**Comment by gawhelan** [comment]
I think we need to change the signature used for middleware functions in order to support optional arguments.

I can see 2 options here: pass `next` as the first argument or pass other arguments as an array.

## Pass `next` as the first argument
```js
// Add middleware to use double separators
join.use((next, parts, separator) => {
  const sep = separator || ' ';
  return next(parts, sep + sep));
});
```

## Pass other arguments as an array
```js
// Add middleware to use double separators
join.use(([parts, separator], next) => {
  const sep = separator || ' ';
  return next(parts, sep + sep));
});
```

Crowdsourced opinions? @fergusmcdonald, @robbiegleeson, @matteobandiera, @vicpada, @ale88sv, @barrymcc94, @xkal36, @oregand

**Comment by fergusmcdonald** [comment]
@gawhelan I think passing `next` as the first argument is tidier. Either works though....

**Comment by robbiegleeson** [comment]
@gawhelan I like the second option - separating `next` from params and passing them in as an `array` looks functionality better. It's clear that `next` is used as the return function. But as @fergusmcdonald says - either works...

**Comment by Oregand** [comment]
I think passing the other arguments as an array seperate from the 'next' fn makes more sense given they are the optional values and looks more readable.

**Comment by gawhelan** [comment]
I kind of agree with all the opinions expressed above, so maybe there is a third option:

## `next` first followed by an array of arguments
```js
function midware(next, [arg1, arg2, ...]) { ... }
```

It does force you to unpack the args array but using array destructuring that is quite painless and I think it slightly improves readability by more clearly separating `next` from the wrapped function arguments.

**Comment by gawhelan** [comment]
Taking some inspiration from Redux middleware I decided to go with the following pattern:

```js
const midware = next => (arg1, arg2, ...) => { ... };
```

I think this more cleanly separates `next` from the wrapped function parameters and has the nice side-effect of significantly simplifying the code required for composing the middleware chain before invocation.
